import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import AuthProvider from "./components/AuthProvider";

import { Dosis } from "next/font/google";

import { Handjet } from "next/font/google";

const handjet = Handjet({ subsets: ["latin"], weight: ["400"] });
const dosis = Dosis({ subsets: ["latin"], weight: ["500"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dosis.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
